### PR TITLE
Improve & cleanup of subprocess function

### PR DESCRIPTION
**Pull request by bitcoinhodler**
I started from your bitcoin-cli-fn-take2 and implemented the suggestions I made on [PR 56](https://github.com/GlacierProtocol/GlacierProtocol/pull/56). See individual commits for comments.

### CODE REVIEW

**Comment by bitcoinhodler** [comment]
I also merged master, which makes for a bit of mess in comparing the two branches; sorry about that.

Start with a8ecaf7 and go from there.

**Comment by bitcoinhodler** [comment]
I'm also thinking it might be better to pass the cmdline args as a list, instead of a string with shell=True. Having the shell parse the cmdline is less clean, and introduces some (probably insignificant) risk of injecting evil things (much like SQL injection). But the main benefit would be to clean up all the argstring mess at all of the call sites. What do you think?

**Comment by bitcoinhodler** [comment]
Pushed a new group of commits with that change. Simplifies a lot of the argstring mess throughout the call sites.

**Comment by ak1n** [comment]
I've been going through the merge-nado...thanks for all the awesome upgrades. I was trying to bash this manually forward without understanding how all the parameters work with lists...python forced me to learn about this and I should have some synthesis shortly. I don't know how to easily do commit-merges (do you just do things manually or do you use the git cherry pick business?) so because of the different fork-points I have been manually-merging. While the list-switch is a bit of a headache seems like there are multiple advantages, including not using shell=True & less likelihood of things breaking with string argument parsing. Thanks again, more soon.

**Comment by ak1n** [comment]
I have integrated the main changes into my master, with subsequent other minor changes. Not sure the best way to contribute back upstream as have made a bunch of other changes - would appreciate any recommendations in this regard. Still some differences in e.g. function names & default variable assignment (rather than explicit passing through calls).

I'll next take a look at what might be involved in non-segwit sequential transactions before moving to tails/veracrypt work. Thanks

**Comment by bitcoinhodler** [comment]
One step at a time...if you could merge this PR here into your branch, then my changes will show up in [GlacierProtocol#56](https://github.com/GlacierProtocol/GlacierProtocol/pull/56). There we can review and merge.

Git can be a pain when you're merging lots of changes to the same code. I use cherry-pick, rebase, and/or merge, depending on the details.

**Pull request closed without merging**
